# -*- coding: utf-8 -*-
"""Ana.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qpigF4PaFwA_FOVE-IEKG8SHyOUYfpp0
"""

def elevado (a):
  operacion = a**2
  return operacion
a=int(input("Ingrese un número para elevar: "))
print("El elevado del numero es: ",elevado(a))